[tool.poetry]
name = "backtrader"
version = "0.1.0"
description = ""
authors = ["bois1616 <github@hexenwoche.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
statsmodels = "^0.14.3"
matplotlib = "^3.9.2"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
